_main/urls.py
import os

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('comments/', include('comments.urls')),
    path('api/', include('api.urls')),
    path('', include('playlists.urls')),
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('playlists/',views.playlists_index, name='api-playlists-index'),
    path('playlists/<int:id>/',views.playlists_detail, name='api-playlists-detail'),
    path('playlists/user-favorites',views.user_favorite_playlists, name='api-user-favorites'),
    path('comments/',views.comments_index,name='api-comments-index'),
    path('comments/playlists/<int:id>/',views.comments_in_playlist,name='api-comments-playlist'),
]

playlists/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.PlaylistIndex.as_view(), name='playlists-index'),    
    path('playlists/<int:pk>/', views.PlaylistDetail.as_view(), name='playlists-detail'),
    path('playlists/create/',views.PlaylistCreate.as_view(), name='playlists-create'),
    path('playlists/<int:pk>/update/', views.PlaylistUpdate.as_view(), name='playlists-update'),
    path('playlists/<int:pk>/delete/', views.PlaylistDelete.as_view(), name='playlists-delete'),
    path('playlists/genre/<str:name>/',views.GenreList.as_view(),name='playlists-genre-list'),
    path('playlists/user/<str:username>/',views.UserList.as_view(),name='playlists-user-list'),
    path('playlists/<int:pk>/removesong/<int:songid>', views.remove_song_in_pl, name='playlists-removesong'),
   	path('playlists/<int:pk>/addsong/', views.add_song_to_pl, name='playlists-addsong'),
   	path('playlists/addgenre',views.add_genre,name='playlists-addgenre'),
    path('playlists/playlist-delete-redirect',views.delete_redirect, name='playlist-delete-redirect')	
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from playlists.models import Playlist
from django.utils import timezone

# Create your models here.
class Comment(models.Model):
    text = models.TextField()
    playlist = models.ForeignKey(Playlist,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    comment_date = models.DateField(default=timezone.now)
    

playlists/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class Artist(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    def natural_key(self):
        return (self.name)
    

class Album(models.Model):
    title = models.CharField(max_length=50)
    release_year = models.IntegerField
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    def natural_key(self):
        return (self.title)

class Song(models.Model):
    title = models.CharField(max_length=50)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True,)
    def __str__(self):
        return self.title
    def natural_key(self):
        if self.album:
            return ({'id': self.id,'title': self.title,'artist': self.artist.name,'album': self.album.title})
        else:
            return ({'id': self.id,'title': self.title,'artist': self.artist.name})

    
class Genre(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    def natural_key(self):
        return (self.name)

class Playlist(models.Model):
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    songs = models.ManyToManyField(Song)
    genres = models.ManyToManyField(Genre)
    description = models.TextField(default="")
    date_created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('playlists-detail', kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from playlists.models import Playlist

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    favorites = models.ManyToManyField(Playlist)
    def __str__(self):
        return self.user.username

playlists/forms.py
from django import forms

class NewPlaylist(forms.Form):
    title = forms.CharField(
        label="create your playlist", 
        max_length=120,  widget= forms.TextInput(
            attrs={'placeholder':'Your amazing playlist'}
        )
    )

class AddSong(forms.Form):
    title = forms.CharField(
        label="Title", 
        max_length=120, 
        widget= forms.TextInput(attrs={'placeholder':'title'}))
    artist = forms.CharField(
        label="Artist", 
        max_length=120,
        widget= forms.TextInput(attrs={'placeholder':'artist'}))
    custom = forms.BooleanField(
        required=False,
        label="Custom?",
        # widget= forms.CheckboxInput()
    )
    # album = forms.CharField(
    #     label="Album", 
    #     max_length=120,
    #     widget= forms.TextInput(attrs={'placeholder':'album'}))

class AddGenre(forms.Form):
    name = forms.CharField(
        label="Name", max_length=120)

playlists/views.py
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from comments.forms import NewComment
from .forms import AddGenre, AddSong, NewPlaylist
# from .lastfm import search_song
from .spotify import find_artist_album_track
from .models import Album, Artist, Genre, Playlist, Song

class PlaylistIndex(ListView):
    model = Playlist
    queryset = Playlist.objects.order_by('-date_created')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = NewPlaylist()
        context['genres'] = Genre.objects.all()
        return context

class PlaylistDetail(DetailView):
    model = Playlist
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = NewComment()
        context['song_form'] = AddSong()
        return context

class PlaylistCreate(LoginRequiredMixin, CreateView):
    model = Playlist
    fields = ['title','genres','description',]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre_form'] = AddGenre()
        return context
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PlaylistUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Playlist
    fields = ['title','description','genres']
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def test_func(self):
        pl = self.get_object()
        if pl.user == self.request.user:
            return True
        else:
            return False

class PlaylistDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Playlist
    success_url = '/playlists/playlist-delete-redirect'
    def test_func(self):
        pl = self.get_object()
        if pl.user == self.request.user:
            return True
        else:
            return False

def delete_redirect(req):
	username = req.user
	return render(req, "playlists/playlist_delete_redirect.html", {'username': username})

class GenreList(ListView):
    model = Playlist
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = NewPlaylist()
        context['genres'] = Genre.objects.all()
        return context
    def get_queryset(self):
        self.genre = get_object_or_404(Genre, name=self.kwargs['name'])
        glist = Genre.objects.get(name=self.genre).playlist_set.all()
        if glist:
            return Genre.objects.get(name=self.genre).playlist_set.all()
        else:
            return Playlist.objects.all()

class UserList(ListView):
    model = Playlist
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = NewPlaylist()
        context['genres'] = Genre.objects.all()
        return context
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        qlist = Playlist.objects.filter(user=user).order_by('-date_created')
        if qlist:
            return qlist
        else:
            return Playlist.objects.all()


@login_required()
def add_song_to_pl(req,pk):
    pl = Playlist.objects.get(pk=pk)
    if req.method == "POST":
        f = AddSong(json.loads(req.body.decode('utf-8')))
        if f.is_valid() and req.user == pl.user:
            (jackie, jenny) = (f.cleaned_data['artist'],f.cleaned_data['title'])
            if f.cleaned_data['custom'] == False:
                try:
                    # track_info = search_song('track.getInfo',jackie,jenny).json()['track']
                    # (artist,album,title) = (track_info['artist']['name'],track_info['album']['title'],track_info['name'],)
                    (artist, album, title) = find_artist_album_track(jackie, jenny)
                    try:
                        ar = Artist.objects.get(name=artist)
                    except:
                        ar = Artist(name=artist)
                        ar.save()
                    try:
                        al = Album.objects.get(title=album)
                    except:
                        al = Album(title=album,artist=ar)
                        al.save()
                    try:
                        son = ar.song_set.get(title=title)
                    except:
                        son = Song(title=title,artist=ar,album=al)
                        son.save()
                    finally:
                        pl.songs.add(son)
                        pl.save()
                except:
                    return JsonResponse({'success': False})
            else:
                try:
                    ar = Artist.objects.get(name=jackie)
                except:
                    ar = Artist(name=jackie)
                    ar.save()
                try:
                    son = ar.song_set.get(title=jenny)
                except:
                    son = Song(title=jenny,artist=ar)
                    son.save()
                finally:
                    pl.songs.add(son)
                    pl.save()
        return JsonResponse({'success': True})

# @login_required()
# def add_song_to_pl(req,pk):
#     pl = Playlist.objects.get(pk=pk)
#     if req.method == "POST":
#         f = AddSong(json.loads(req.body.decode('utf-8')))
#         if f.is_valid():
#             if req.user == pl.user:
#                 (artist, album, title) = (f.cleaned_data['artist'], f.cleaned_data['album'],f.cleaned_data['title'])
#                 try:
#                     ar = Artist.objects.get(name=artist)
#                 except:
#                     ar = Artist(name=artist)
#                     ar.save()
#                 try:
#                     al = Album.objects.get(title=album)
#                 except:
#                     al = Album(title=album,artist=ar)
#                     al.save()
#                 try:
#                     son = Song.Objects.get(title=title)
#                 except:
#                     son = Song(title=title,artist=ar,album=al)
#                     son.save()
#                 finally:
#                     pl.songs.add(son)
#                     pl.save()
#         return JsonResponse({'success': 'yes'})

@login_required()
def remove_song_in_pl(req,pk,songid):
    if req.method == "POST":
        pl = Playlist.objects.get(pk=pk)
        son = Song.objects.get(pk=songid)
        if req.user == pl.user:
            pl.songs.remove(son)
            pl.save()
    return JsonResponse({'success': True})

@login_required()
def add_genre(req):
    if req.method == "POST":
        genre = AddGenre(req.POST)
        if genre.is_valid():
            g = Genre(name=genre.cleaned_data['name'])
            g.save()
    return redirect('playlists-create')

templates/playlists/create.html
{% extends "../layout.html" %}

{% block title %}
Create new playlist
{% endblock %}

{% block content %}
    <h1>Create playlist</h1>

    <form action="{% url 'playlists-create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="create">
    </form>
{% endblock %}

templates/playlists/detail.html
{% extends "../layout.html" %}
{% block title %}
Playlists - {{pl.title}}
{% endblock %}
{% block content %}
<div class="playlists-detail">
    <div class="header">
        <div class="text">
            <h1>{{pl.title}}</h1>
            <h4>created by {{pl.user_id}}</h4>
        </div>
        <div class="buttons">
            {%if user == pl.user_id%}
            <button>Add new songs</button>    
            {% else %}
            <form action="{% url 'users-addtofav' pl.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Add to favorites</button>
            </form>
            {%endif%}
        </div>
     
    </div>

    <div class="list">
        <ol>
            {% for s in songs %}
                <li>{{s.title}}</li>
            {% endfor %}
        </ol>
            
        <article>
            {{pl.description}}
        </article>

    </div>
    
    <section class="comments">
        <h2>comments</h2>
        <form action="{% url 'comments-create' pl.id%}" method="post">
            {% csrf_token %}
            {{comment_form}}
            <input class="input-submit" type="submit" value="submit">
        </form>
        {%for c in comments%}
        <div class="comment">
            <h4>{{c.user}}</h4>
            <p>{{c.text}}</p>
        </div>
        {%endfor%}

    </section>


    {%if user == pl.user_id%}   
    <div class="add-new">
        <h3> Add new songs</h3>
        <form action="{% url 'playlists-detail' id=pl.id %}" method="post">
            {% csrf_token %}
            {{song_form}}
            <input type="submit" value="add">
        </form>
    </div>
    {%endif%}
</div>


{% endblock %}

templates/playlists/index.html
{% extends "../layout.html" %}

{% block title %}
The best playlists
{% endblock %}

{% block content %}
<div class="playlists-home">
    <section class="display">
        <div class="display-text">
            <h3>hot this week:</h3>
            <h1> <a href="{% url 'playlists-detail' pl.first.pk %}">{{pl.first}}</a></h1>
        </div>
        
        <div class="create">
            <form action="{% url 'playlists-create' %}" method="post">
                {%csrf_token%}
                {{form}}
                <input type="submit" value="create playlist">
            </form>    
        </div>
    </section>
    <section class="catalog">
        <h3>new playlists:</h3>
        <ul>
            {% for p in pl.all%}
            <li style="background-image: url('/static/playlists/img/DSCF0321.JPG');background-size: 100%;">
                <h3><a href="{% url 'playlists-detail' p.pk %}">{{p.title}}</a></h3>
                <h4>by {{p.user_id}}</h4>
            </li>
            {% endfor %}
        </ul>
    </section>
</div>
{% endblock %}

templates/playlists/playlist_confirm_delete.html
{% extends "../modal.html" %}

{% block title %}
Delete playlist
{% endblock %}

{% block content %}
    <h1>Delete playlist?</h1>
    
    <form action="#" method="post">
        {% csrf_token %}
        <input type="submit" value="confirm">
    </form>
    <button class="button-outline">go back</a>

    <script>
        let header = document.querySelector(".header");
        let closeButton = document.querySelector(".button-outline")
        header.remove();

        closeButton.addEventListener('click', () => {
            window.parent.vueTracklist.closeModal()
        })

    </script>
{% endblock %}

templates/playlists/playlist_delete_redirect.html
{% extends "../modal.html" %}

{% block content %}
<script>
    let header = document.querySelector(".header");
    header.remove();
</script>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        window.parent.location.pathname = "/"})
</script>

{% endblock %}

templates/playlists/playlist_detail.html
{% extends "../layout.html" %}
{% load static %}
{% block title %}
Playlists - {{object.title}}
{% endblock %}
{% block content %}
<div class="playlists-detail">
    <section class="header" style="background-image: url(/static/img/{{object.genres.first}}-header.jpg);">
        <div class="text">
            <h1>{{object.title}}</h1>
            <a href="{% url 'playlists-user-list' object.user.username %}"><h4>created by {{object.user.username}}</h4></a>
        </div>
    </section>

    <section class="content">
        <div class="list" id="vue-playlist">            
            <ol class="tracklist">
                {% if user.username and not object.user == user%}
                <vplfavorite :playlistid="playlistid"></vplfavorite>
                    <!-- {%if object in user.profile.favorites.all%} -->
                    <!-- <vplfavorite :isfavorite="true"></vplfavorite> -->
                    <!-- {% else %} -->
                    <!-- {% endif%}    -->
                {%endif%}
                {% if object.user == user%} 
                <vtracklist 
                    :songs="songs" 
                    :iscreator="true" 
                    :deleteurl="'{% url 'playlists-delete' object.pk %}'"
                    @deleteplaylist="openModal"
                    @songremoved="getSongs">
                </vtracklist>
                {% else %}
                <vtracklist :songs="songs" @songremoved="getSongs"></vtracklist>
                {%endif%}
            </ol>                        
            <article>
                <vpldescription 
                    :description="description" 
                    :genres="genres" 
                    :url="'{% url 'playlists-index' %}playlists/genre/'">
                </vpldescription>
                {% if user == object.user%}
                <vsongadder :notfound="notfound" @addedsong="getSongs"></vsongadder>
                {% endif %} 
            </article>


            <div v-if="modal.length > 1" class="auth-iframe small">
                <iframe :src="modal" frameborder="0"></iframe>
                <!-- <iframe src="{% url 'users-create' %}" frameborder="0"></iframe> -->
                <button class="close-modal material-icons" @click="closeModal()"></button>
            </div>
        </div>    
        <section id="vue-comments" class="comments">
            <h3>comments</h3>       
            <div class="comment-add">
                {% if user.username %}
                <vaddcomment @addedcomment="getComments">                
                </vaddcomment>
                {% else %}
                <span>to join the discussion, <a href="{% url 'login' %}">login</a> or <a href="{% url 'users-create' %}">create an account.</a></span>
                {% endif %}
            </div>
            
            <div class="comment-list">
                <vcommentlist 
                    v-for="(c, idx) in comments"
                    :key="idx"
                    :text="c.fields.text"
                    :user="c.fields.user[0]"
                    :comment_date="c.fields.comment_date"
                    :url="'{% url 'playlists-index' %}users/detail/' + c.fields.user[0]">
                </vcommentlist>
            </div>


            
        </section>
    </section>  
</div>

<script src="{% static 'vue/playlist_tracklist.js' %}"></script>
<script src="{% static 'vue/playlist_comments.js' %}"></script>

{% endblock %}

templates/playlists/playlist_form.html
{% extends "../layout.html" %}

{% block title %}
Create new playlist
{% endblock %}

{% block content %}
    <div class="playlists-form">
        <form class="add-playlist" action="#" method="post">
        	<h1>Create playlist</h1>
            {% csrf_token %}
            {{ form }}      
            <input type="submit" value="create">
        </form>
    </div>    
{% endblock %}

templates/playlists/playlist_list.html
{% extends "../layout.html" %}

{% block title %}
Playitt
{% endblock %}

{% block content %}
<div class="playlists-home">
    <section class="display" style="background-image: url(/static/img/{{object_list.first.genres.first}}-header.jpg);">
        <div class="display-jenny">
            <div class="display-jackie">
                <span>hot this week</span>
                <a href="{% url 'playlists-detail' object_list.first.pk %}"><h2> {{object_list.first}}</h2></a>
            </div>            
        </div> 
    </section>

    <section class="catalog">
        <div class="catalog-list">
            <div class="catalog-list-header">
                <h4>create playlists, choose your favorites, comment, share</h4>       
            </div>
            <div class="catalog-create">
                <form action="{% url 'playlists-create' %}" method="post">
                    {%csrf_token%}
                    {{form}}
                    <input type="submit" value="create">
                </form>    
            </div>
            <ul>
                {% for p in object_list.all%}
                <li class="playlist-card">
                    <div class="header">
                        <div class="header-text">
                            <a class="playlist-link" href="{% url 'playlists-detail' p.pk %}"><h3>{{p.title}}</h3></a>
                            <h4>by {{p.user.username}}</h4>
                        </div>
                        <span>
                            {{p.profile_set.count}}<i class="material-icons">stars</i>
                        </span>
                    </div>

                    <p> featuring
                    {% for s in p.songs.all|slice:":5"  %}
                        {{s.artist}},
                    {% endfor %}
                        and more
                    </p>
                    <a class="playlist-link" href="{% url 'playlists-detail' p.pk %}#vue-comments">
                        <span>{{p.comment_set.count}} {{ p.comment_set.count|pluralize:"comment,comments" }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="catalog-sidebar">
            <div class="header">
                <h2>what music do you love?</h2>
            </div>
            <div class="content">
                <h4>genres</h4>
                <ul>
                    {%for g in genres%}
                        <li><a href="{% url 'playlists-genre-list' g.name %}">{{g.name}}</a></li>
                    {%endfor%}                    
                </ul>
                {% if user.username %}
                <h4>creations</h4>
                <ul>
                    {%for g in user.playlist_set.all%}
                        <li><a href="{% url 'playlists-detail' g.pk %}">{{g.title}}</a></li>
                    {%endfor%}                    
                </ul>
                <h4>favourites</h4>
                <ul>
                    {%for g in user.profile.favorites.all%}
                        <li><a href="{% url 'playlists-detail' g.pk %}">{{g.title}}</a></li>
                    {%endfor%}                    
                </ul>
                {% endif %}
            </div>           
        </div>
    </section>
</div>

<script>
    let cards = document.querySelectorAll(".playlist-card")
    cards.forEach(el => {
        let elLink = el.querySelector(".playlist-link").getAttribute('href')
        el.addEventListener("click", () => {
            window.location = elLink;
        })
    })
</script>

{% endblock %}